name: Deploy to GitHub Pages

on:
  push:
    branches: ['main'] # Vérifie que ta branche s'appelle bien main (ou master)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. On installe Bun au lieu de Node.js
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # 2. On installe les dépendances avec Bun
      - name: Install dependencies
        run: bun install

      # 3. On build le projet avec Bun
      - name: Build
        run: bun run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # C'est le dossier généré par Vite

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4